name: FlightPads
version: 1.1
main: com.itsazza.launchpads.LaunchPads
api-version: 1.13
authors: [ ItsAZZA, skuralll ]
website: https://skuralll.com/
softdepend: [ Kotlin ]
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:1.6.0'
commands:
  flightpads:
    aliases: ["flightpad"]